name: Ollama Code Review

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: write
  pull-requests: write

jobs:
  code-review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v42

      - name: Install Ollama
        run: |
          curl -fsSL https://ollama.com/install.sh | sh
          ollama serve &
          for i in {1..30}; do
            if curl -s http://localhost:11434 > /dev/null; then
              echo "Ollama server is ready."
              break
            fi
            echo "Waiting for Ollama server to start..."
            sleep 2
          done
          ollama pull codellama || { echo "Failed to pull codellama model"; exit 1; }

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Identify changed files
        run: |
          git diff --name-only origin/${{ github.base_ref }}...${{ github.head_ref }} -- '*.py' > changed_files.txt
          echo "Changed files:"

      - name: Run Pylint Fix Script
        run: |
          python fix_pylint_issues.py

      - name: Confirm Changes
        uses: hmarr/auto-approve-action@v3
        with:
          message: |
            The following files have been modified by Ollama and Pylint:
            $(git status --short)

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Auto-fix Pylint issues using Ollama"
          git push origin ${{ github.head_ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Code Review
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          GITHUB_REPOSITORY_OWNER: ${{ github.repository_owner }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_SHA: ${{ github.event.pull_request.head.sha }}
          FILE_PATTERN: '**/*.{ts,tsx}'
        run: |
          echo "Starting code review process..."
          python src/main.py

      - name: Cleanup
        if: always()
        run: |
          sudo systemctl stop ollama || pkill ollama
