name: Ollama Code Review

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: write
  pull-requests: write

jobs:
  code-review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v42
    
      - name: Install Ollama
        run: |
          curl -fsSL https://ollama.com/install.sh | sh
          ollama serve &
          for i in {1..30}; do
            if curl -s http://localhost:11434 > /dev/null; then
              echo "Ollama server is ready."
              break
            fi
            echo "Waiting for Ollama server to start..."
            sleep 2
          done
          ollama pull codellama || { echo "Failed to pull codellama model"; exit 1; }

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Fix PEP 8 and format files with Black
        run: |
          echo "Identifying files with changes..."
          git diff --name-only origin/${{ github.base_ref }}...${{ github.head_ref }} -- '*.py' > changed_files.txt
          echo "Files with changes:"
          
          echo "Applying autopep8 and black to changed files..."
          while IFS= read -r file; do
            echo "Fixing file: $file"
            autopep8 --in-place --global-config /dev/null --max-line-length 120 "$file"
            black "$file"
          done < changed_files.txt
          echo "PEP 8 fixes and formatting applied to changed files."
          rm -f changed_files.txt  # Delete the temporary file

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          if [ -n "$(git status --porcelain)" ]; then
            echo "Changes detected. Committing and pushing..."
            git add .
            git commit -m "Auto-fix PEP 8 issues"
            git push origin ${{ github.head_ref }}
          else
            echo "No changes to commit. Skipping push."
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Get list of changed Python files
        id: changed
        run: |
          files=$(git diff --name-only origin/${{ github.base_ref }}...HEAD -- '*.py')
          echo "$files"
          echo "CHANGED_FILES<<EOF" >> $GITHUB_ENV
          echo "$files" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Run cleanup tools only on changed files
        if: env.CHANGED_FILES != ''
        run: |
          for file in $CHANGED_FILES; do
            echo "🔧 Processing $file"
            autoflake --remove-all-unused-imports --remove-unused-variables --in-place --recursive "$file" 
            isort --recursive --apply "$file" 
            pydocstring "$file"
            echo "🔍 Running vulture (won't fail on warnings)..."
            vulture "$file" || echo "Vulture found issues in $file"
            docformatter --in-place "$file"
          done

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          if [ -n "$(git status --porcelain)" ]; then
            echo "Changes detected. Committing and pushing..."
            git add .
            git commit -m "Auto-fix pylint  issues"
            git push origin ${{ github.head_ref }}
          else
            echo "No changes to commit. Skipping push."
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Code Review
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          GITHUB_REPOSITORY_OWNER: ${{ github.repository_owner }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_SHA: ${{ github.event.pull_request.head.sha }}
          FILE_PATTERN: '**/*.{ts,tsx}'
        run: |
          echo "Starting code review process..."
          python src/main.py

      - name: Send Slack Notification
        if: github.event_name == 'pull_request' && github.event.action == 'opened'
        uses: slackapi/slack-github-action@v1.23.0
        with:
          channel-id: ${{ secrets.SLACK_CHANNEL_ID }}
          payload: |
            {
              "username": "GitHub PR Bot",
              "attachments": [
                {
                  "color": "good",
                  "title": "New Pull Request Created",
                  "text": "A new pull request has been created in *${{ github.repository }}*.",
                  "fields": [
                    {
                      "title": "PR Title",
                      "value": "${{ github.event.pull_request.title }}",
                      "short": true
                    },
                    {
                      "title": "PR URL",
                      "value": "<${{ github.event.pull_request.html_url }}|View Pull Request>",
                      "short": false
                    }
                  ]
                }
              ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_TOKEN }}

      - name: Cleanup
        if: always()
        run: |
          sudo systemctl stop ollama || pkill ollama
